apiVersion: v1
kind: ServiceAccount
metadata:
  name: runner-executor
  namespace: gitlab
#imagePullSecrets:
#- name: dockersecret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gitlab
  name: runner-executor
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: gitlab
  name: runner-executor-rolebinding
subjects:
- kind: ServiceAccount
  name: runner-executor
  namespace: gitlab
roleRef:
  kind: Role
  name: runner-executor
  apiGroup: rbac.authorization.k8s.io
